version: '3.9'

services:
  main:
    container_name: main
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
      - '9229:9229'
    command: npm run start:dev
    networks:
      - films-net
    depends_on:
      - redis
    restart: unless-stopped
  redis:
    container_name: redis
    image: 'redis:alpine3.15'
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - films-net
  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:${REDIS_PORT}
    ports:
      - ${REDIS_COMMANDER_PORT}:${REDIS_COMMANDER_PORT}
    networks:
      - films-net
    depends_on:
      - redis

networks:
  films-net:
    driver: bridge

volumes:
  main: